### ISSUE TITLE
qemu 6.x: qmpbackup fails to get bitmaps

### ISSUE THREAD

**Issue by Wyk72** [abbbi/qmpbackup#2]
I am trying to test your program but I am experiencing a big problem:

- first "full" backup runs OK (very slowly, but the qcow file  is created correctly)
- the "incremental" backup fails, both in "auto" and "inc" modes:

root@immortality-lvm:~# qmpbackup --socket /tmp/qmp-socket backup --level auto --monthly --target /aoe

[2022-01-24 17:02:05,267]    INFO  Version: 0.5
[2022-01-24 17:02:05,268]    INFO  Backup target directory: /aoe/2022-01
[2022-01-24 17:02:05,268]    INFO  FULL Backup operation: "/aoe/2022-01/drive-virtio-disk1/FULL-1643040125"
Traceback (most recent call last):
  File "/usr/bin/qmpbackup", line 4, in <module>
    __import__('pkg_resources').run_script('qmpbackup==0.5', 'qmpbackup')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.9/site-packages/qmpbackup-0.5-py3.9.egg/EGG-INFO/scripts/qmpbackup", line 240, in <module>
  File "/usr/lib/python3.9/site-packages/qmpbackup-0.5-py3.9.egg/libqmpbackup/qmpcommon.py", line 181, in do_full_backup_with_bitmap
  File "/usr/lib/python3.9/site-packages/qmpbackup-0.5-py3.9.egg/libqmpbackup/qmpcommon.py", line 92, in check_qmp_return
Exception: Bitmap already exists: qmpbackup-drive-virtio-disk1

root@immortality-lvm:~# qmpbackup --socket /tmp/qmp-socket backup --level inc --monthly --target /aoe
[2022-01-24 17:02:18,890]    INFO  Version: 0.5
[2022-01-24 17:02:18,891]    INFO  Backup target directory: /aoe/2022-01
[2022-01-24 17:02:18,891]   ERROR  Incremental backup requested but no active bitmap has been found.

"no active bitmap" is reported but the dirty bitmap is inside the QCOW file:

# qmpbackup --socket /tmp/qmp-socket --debug info --show blockdev

2022-01-24 17:03:49,219]    INFO  VM Block Device Information:
[2022-01-24 17:03:49,219]    INFO  [
    {
        "device": "pflash0",
        "inserted": {
            "backing_file_depth": 0,
            "bps": 0,
            "bps_rd": 0,
            "bps_wr": 0,
            "cache": {
                "direct": false,
                "no-flush": false,
                "writeback": true
            },
            "detect_zeroes": "off",
            "drv": "raw",
            "encrypted": false,
            "file": "/usr/share/OVMF/OVMF_CODE.fd",
            "image": {
                "actual-size": 3657728,
                "dirty-flag": false,
                "filename": "/usr/share/OVMF/OVMF_CODE.fd",
                "format": "raw",
                "virtual-size": 3653632
            },
            "iops": 0,
            "iops_rd": 0,
            "iops_wr": 0,
            "node-name": "#block157",
            "ro": true,
            "write_threshold": 0
        },
        "locked": false,
        "qdev": "/machine/system.flash0",
        "removable": false,
        "type": "unknown"
    },
    {
        "device": "pflash1",
        "inserted": {
            "backing_file_depth": 0,
            "bps": 0,
            "bps_rd": 0,
            "bps_wr": 0,
            "cache": {
                "direct": false,
                "no-flush": false,
                "writeback": true
            },
            "detect_zeroes": "off",
            "drv": "raw",
            "encrypted": false,
            "file": "/dev/shm/OVMF_VARS.fd",
            "image": {
                "actual-size": 540672,
                "dirty-flag": false,
                "filename": "/dev/shm/OVMF_VARS.fd",
                "format": "raw",
                "virtual-size": 540672
            },
            "iops": 0,
            "iops_rd": 0,
            "iops_wr": 0,
            "node-name": "#block393",
            "ro": false,
            "write_threshold": 0
        },
        "locked": false,
        "qdev": "/machine/system.flash1",
        "removable": false,
        "type": "unknown"
    },
    {
        "device": "drive-virtio-disk1",
        "inserted": {
            "backing_file_depth": 0,
            "bps": 0,
            "bps_rd": 0,
            "bps_wr": 0,
            "cache": {
                "direct": false,
                "no-flush": false,
                "writeback": true
            },
            "detect_zeroes": "unmap",
            "dirty-bitmaps": [
                {
                    "busy": false,
                    "count": 1093664768,
                    "granularity": 65536,
                    "name": "qmpbackup-drive-virtio-disk1",
                    "persistent": true,
                    "recording": true
                }
            ],
            "drv": "qcow2",
            "encrypted": false,
            "file": "/imm-100/wyk2022.qcow2",
            "image": {
                "actual-size": 53120364544,
                "cluster-size": 262144,
                "dirty-flag": true,
                "filename": "/imm-100/wyk2022.qcow2",
                "format": "qcow2",
                "format-specific": {
                    "data": {
                        "compat": "1.1",
                        "compression-type": "zlib",
                        "corrupt": false,
                        "extended-l2": true,
                        "lazy-refcounts": true,
                        "refcount-bits": 16
                    },
                    "type": "qcow2"
                },
                "virtual-size": 107374182400
            },
            "iops": 0,
            "iops_rd": 0,
            "iops_wr": 0,
            "node-name": "#block522",
            "ro": false,
            "write_threshold": 0
        },
        "io-status": "ok",
        "locked": false,
        "qdev": "/machine/peripheral/virtio-disk1/virtio-backend",
        "removable": false,
        "type": "unknown"
    }
]

The durty bitmap is there,

BUT

# qmpbackup --socket /tmp/qmp-socket --debug info --show bitmaps
[2022-01-24 17:04:46,972]    INFO  Version: 0.5
[2022-01-24 17:04:46,973]    INFO  Bitmaps:
[2022-01-24 17:04:46,973]    INFO  No bitmaps found for device: "drive-virtio-disk1"

Am I doing something wrong ?

**Comment by abbbi** [comment]
pretty strange, has_bitmap is set in libqmpbackup/vm.py:

https://github.com/abbbi/qmpbackup/blob/master/libqmpbackup/vm.py#L24

the full backup already fails to define the bitmap according to your log:

```
do_full_backup_with_bitmap
File "/usr/lib/python3.9/site-packages/qmpbackup-0.5-py3.9.egg/libqmpbackup/qmpcommon.py", line 92, in check_qmp_return
Exception: Bitmap already exists: qmpbackup-drive-virtio-disk1
```

**Comment by abbbi** [comment]
I attempted to reproduce the situation but if i fail. The only difference i can spot is that the bitmap that is shown in your blockdev output is not marked as active. In my case, the bitmap information looks something like this:

```
            "dirty-bitmaps": [
                {
                    "busy": false,
                    "count": 0,
                    "granularity": 65536,
                    "name": "qmpbackup-ide0-hd0",
                    "persistent": true,
                    "recording": true,
                    "status": "active"
                }
            ],

```

note the status: active flag here, this is entirely missing in your output and that appears to be strange for me.

**Comment by Wyk72** [comment]
I am trying to dissect the problem. Looks weird to me too. Maybe it's a musl/Alpine quirk, qemu is 6.1.

BTW, do you think it's possible to expose a snapshot as an NBD device (via socket, I guess), so I can "pull" the data from there ? QEMU "pushing" the snapshot is very, very slow in my setup, takes more than half an hour to copy 45GB of data, also slowing down the guest OS in the process, it almost freezes.

I'd like to avoid virsh if possible.

**Comment by abbbi** [comment]
> BTW, do you think it's possible to expose a snapshot as an NBD device (via socket, I guess), so I can "pull" the data from there ? QEMU "pushing" the snapshot is very, very slow in my setup, takes more than half an hour to copy 45GB of data, also slowing down the guest OS in the process, it almost freezes.

yes, it should also be possible to expose the data via nbd, using the pull based approach, but its not implemented in qmpbackup. currently. I use the pull based approach in combination for libvirt in [virtnbdbackup](https://github.com/abbbi/virtnbdbackup)

**Comment by Wyk72** [comment]
I see. I also checked the documentation, and QEMU 6.1 has quite different bitmaps status codes, e.g. "active" is not supported anymore.

"Active: This bitmap is recording new writes.

(This is now +recording -busy.)"


https://qemu-project.gitlab.io/qemu/interop/bitmaps.html

I have managed to use a shell script to send qmp commands directly to the QMP socket, I'll try to implement something, with very basic functionality, to achieve an incremental backup solution like you did, using qcow2 files.

I am trying to avoid zfs/btrfs and go for a thin/lvm solution for VM storage, unfortunately LVM does not have a proper "send" function like zfs/btrfs (there are some hacks around github, but not quite up to the task).

**Comment by abbbi** [comment]
> I see. I also checked the documentation, and QEMU 6.1 has quite different bitmaps status codes, e.g. "active" is not supported anymore.
> 
> "Active: This bitmap is recording new writes.
> 
> (This is now +recording -busy.)"
> 
> https://qemu-project.gitlab.io/qemu/interop/bitmaps.html

okey, that would mean it should fail somewhere while attempting to detect the bitmap status, still i dont undersand how that failure leads to the situation you faced. Guess i need to test with newer qemu versions, might take some time until i get to that.

**Comment by abbbi** [comment]
been able to reproduce with qemu 6.0
Check fix in master.

**Comment by abbbi** [comment]
Fixed in recent release.
